server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/securityForm
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




